spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase_db
    username: root
    password: root

  liquibase:
    change-log: classpath:/db/changelog/app-changelog.xml
    default-schema: liquibase_db